version: '3.8' # 使用 3.8 版本，但你可以根据需要选择其他版本
services:
  whois:
    image: darkqiank/whois:latest
    container_name: whois
    ports:
      - "4567:4567" # 将容器的 4567 端口映射到宿主机的 4567 端口
    restart: unless-stopped # 容器退出时重启策略
