name: push-to-ecr

on:
  push:
    branches: [ master ]

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.18

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli
        
    - name: Login to Amazon ECR and Docker
      id: login
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      
    - name: Build and push Docker image
      env:
        IMAGE_NAME: whois
        TAG: latest
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      run: |
        # Build the Docker image
        docker build -t $ECR_REGISTRY/$IMAGE_NAME:$TAG .
        # Push the Docker image to ECR
        docker push $ECR_REGISTRY/$IMAGE_NAME:$TAG

